export const selectSizeStyles = {
  xs: {
    text: "text-xs",
    select: "py-[5px] pl-2.5 pr-7",
    chevron: "px-1.5",
    option: "px-2.5 py-1.5",
    multipleWrap: "-ms-1.5",
    multipleItem: "ps-1.5 pe-[calc(theme(space[1.5])-1px)]",
    height: 28,
  },
  sm: {
    text: "text-sm",
    select: "py-[5px] pl-3 pr-8",
    chevron: "px-2",
    option: "px-3 py-1.5",
    multipleWrap: "-ms-2",
    multipleItem: "ps-2 pe-[calc(theme(space.2)-1px)]",
    height: 32,
  },
  md: {
    text: "text-base",
    select: "py-[5px] pl-3.5 pr-8",
    chevron: "px-2",
    option: "px-3.5 py-1.5",
    multipleWrap: "-ms-2",
    multipleItem: "ps-2 pe-[calc(theme(space.2)-1px)]",
    height: 36,
  },
  lg: {
    text: "text-base",
    select: "py-[7px] pl-4 pr-10",
    chevron: "px-2",
    option: "px-4 py-2",
    multipleWrap: "-ms-2",
    multipleItem: "ps-2 pe-[calc(theme(space.2)-1px)]",
    height: 40,
  },
  xl: {
    text: "text-lg",
    select: "py-[7px] pl-4 pr-10",
    chevron: "px-2.5",
    option: "px-4 py-2",
    multipleWrap: "-ms-2.5",
    multipleItem: "ps-2.5 pe-[calc(theme(space[2.5])-1px)]",
    height: 44,
  },
};
