name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: huijiewei/resolid

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install Dependencies
        shell: "bash"
        run: |
          cd $GITHUB_WORKSPACE
          pnpm install

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          pnpm run --filter @resolid/remix-plugins build

      - name: Publish
        run: |
          cd $GITHUB_WORKSPACE
          pnpm publish --filter @resolid/remix-plugins --no-git-checks --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
