[build]
command = "npm run website:netlify"
publish = "website/build/client"

[[headers]]
for = "/manifest.webmanifest"
[headers.values]
Content-Type = "application/manifest+json"
Cache-Control = "public, max-age=3600"

[[headers]]
for = "/(favicon|apple-touch-icon).(ico|svg|png)"
[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "/images/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/icons/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
